### ISSUE TITLE
task-launcher-cloudfoundry-sink-rabbit : error on deployment

### ISSUE THREAD

**Issue by nchandrappa** [spring-cloud-stream-app-starters/tasklauncher-cloudfoundry#6]
On deploying a stream with **task-launcher-cloudfoundry-sink-rabbit**(maven://org.springframework.cloud.stream.app:task-launcher-cloudfoundry-sink-rabbit:1.2.0.RC1) , boot app doesn't start and fails with following exception 

```
 Reason: Failed to convert property value of type 'java.lang.String' to required type 'boolean' for property 'skipSslValidation'; nested exception is org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [boolean] 
```

**Comment by cppwfs** [comment]
This looks to be an issue where the spring.cloud.task.version is using snapshot vs. release.  Will update.

**Comment by sabbyanandan** [comment]
This has been resolved. Please try Bacon.RELEASE -> http://bit.ly/Bacon-RELEASE-stream-applications-rabbit-maven
